/* Generated by wayland-scanner 1.15.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

extern const struct wl_interface gtk_surface1_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&gtk_surface1_interface,
	&wl_surface_interface,
	&gtk_surface1_interface,
};

static const struct wl_message gtk_shell1_requests[] = {
	{ "get_gtk_surface", "no", types + 6 },
	{ "set_startup_id", "?s", types + 0 },
	{ "system_bell", "?o", types + 8 },
};

static const struct wl_message gtk_shell1_events[] = {
	{ "capabilities", "u", types + 0 },
};

const struct wl_interface gtk_shell1_interface = {
	"gtk_shell1", 1,
	3, gtk_shell1_requests,
	1, gtk_shell1_events,
};

static const struct wl_message gtk_surface1_requests[] = {
	{ "set_dbus_properties", "?s?s?s?s?s?s", types + 0 },
	{ "set_modal", "", types + 0 },
	{ "unset_modal", "", types + 0 },
	{ "present", "u", types + 0 },
};

static const struct wl_message gtk_surface1_events[] = {
	{ "configure", "a", types + 0 },
};

const struct wl_interface gtk_surface1_interface = {
	"gtk_surface1", 1,
	4, gtk_surface1_requests,
	1, gtk_surface1_events,
};

